version: 0.2
phases:
  install:
    commands:
      - n 14.18.3
  pre_build:
    commands:
      - echo Installing source NPM dependencies........
      - npm install
  build:
    commands:
      #build
      - echo Building...
      - npm build
artifacts:
  files:
    - "**/*"
